# mypy: ignore-errors

"""add customer history table 3

Revision ID: 03dfb34b4892
Revises: 49adff85afd0
Create Date: 2026-08-31 21:56:07.473688

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03dfb34b4892"
down_revision: Union[str, Sequence[str], None] = "49adff85afd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_status_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "old_status",
            sa.Enum(
                "NEW",
                "PENDING_VERIFICATION",
                "VERIFIED",
                "SUSPENDED",
                "REJECTED",
                name="customerstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "NEW",
                "PENDING_VERIFICATION",
                "VERIFIED",
                "SUSPENDED",
                "REJECTED",
                name="customerstatus",
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.UUID(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer_status_history")
    # ### end Alembic commands ###
