# mypy: ignore-errors

"""update Audit Event Types

Revision ID: 06eed7cb035f
Revises: e077a89460fd
Create Date: 2026-08-31 20:01:15.081845

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06eed7cb035f"
down_revision: Union[str, Sequence[str], None] = "e077a89460fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'CUSTOMER_CREATED'")
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'CUSTOMER_UPDATED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
