# mypy: ignore-errors

"""add task assignment rules

Revision ID: 09731755d9af
Revises: 2f2805c9631f
Create Date: 2026-10-02 14:18:35.151433

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09731755d9af"
down_revision: Union[str, Sequence[str], None] = "2f2805c9631f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audit_events = [
        "TASK_ASSIGNMENT_RULE_CREATED",
        "TASK_ASSIGNMENT_RULE_UPDATED",
        "TASK_ASSIGNMENT_RULE_STATUS_CHANGED",
        "TASK_ASSIGNMENT_RULE_APPLIED",
        "TASK_AUTO_ASSIGNED",
    ]

    for event in audit_events:
        op.execute(f"ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS '{event}'")

    op.create_table(
        "task_assignment_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("workflow_step_id", sa.UUID(), nullable=True),
        sa.Column(
            "conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "strategy",
            sa.Enum("LEAST_LOADED", name="task_assignment_strategy"),
            server_default="LEAST_LOADED",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_task_assignment_rules_created_by_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name="fk_task_assignment_rules_workflow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["workflow_steps.id"],
            name="fk_task_assignment_rules_workflow_step",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_task_assignment_rules",
        ),
        sa.UniqueConstraint("name", name="uq_task_assignment_rules_name"),
    )
    op.create_index(
        op.f("ix_task_assignment_rules_created_by"),
        "task_assignment_rules",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_rules_is_active"),
        "task_assignment_rules",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_rules_name"),
        "task_assignment_rules",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_rules_priority"),
        "task_assignment_rules",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_rules_workflow_id"),
        "task_assignment_rules",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_rules_workflow_step_id"),
        "task_assignment_rules",
        ["workflow_step_id"],
        unique=False,
    )
    op.add_column("tasks", sa.Column("assignment_rule_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_tasks_assignment_rule_id"),
        "tasks",
        ["assignment_rule_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_tasks_assignment_rule",
        "tasks",
        "task_assignment_rules",
        ["assignment_rule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "users", sa.Column("department", sa.String(length=100), nullable=True)
    )
    op.create_index(op.f("ix_users_department"), "users", ["department"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_department"), table_name="users")
    op.drop_column("users", "department")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_assignment_rule_id"), table_name="tasks")
    op.drop_column("tasks", "assignment_rule_id")
    op.drop_index(
        op.f("ix_task_assignment_rules_workflow_step_id"),
        table_name="task_assignment_rules",
    )
    op.drop_index(
        op.f("ix_task_assignment_rules_workflow_id"), table_name="task_assignment_rules"
    )
    op.drop_index(
        op.f("ix_task_assignment_rules_priority"), table_name="task_assignment_rules"
    )
    op.drop_index(
        op.f("ix_task_assignment_rules_name"), table_name="task_assignment_rules"
    )
    op.drop_index(
        op.f("ix_task_assignment_rules_is_active"), table_name="task_assignment_rules"
    )
    op.drop_index(
        op.f("ix_task_assignment_rules_created_by"), table_name="task_assignment_rules"
    )
    op.drop_table("task_assignment_rules")
    # ### end Alembic commands ###
