# mypy: ignore-errors

"""create knowledge document chunks

Revision ID: 145bb8fa765d
Revises: e01628670ad9
Create Date: 2026-09-18 00:43:32.850512

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "145bb8fa765d"
down_revision: Union[str, Sequence[str], None] = "e01628670ad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("knowledge_document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_document_id"], ["knowledge_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_document_chunks_knowledge_document_id"),
        "knowledge_document_chunks",
        ["knowledge_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_knowledge_document_chunks_knowledge_document_id"),
        table_name="knowledge_document_chunks",
    )
    op.drop_table("knowledge_document_chunks")
    # ### end Alembic commands ###
