# mypy: ignore-errors

"""update audit event type

Revision ID: 1ac1b4bd68c2
Revises: adc91160d501
Create Date: 2026-09-12 02:17:27.984888

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ac1b4bd68c2"
down_revision: Union[str, Sequence[str], None] = "adc91160d501"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'OCR_REQUESTED'")
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'OCR_COMPLETED'")
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'OCR_FAILED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
