# mypy: ignore-errors

"""create aml rules

Revision ID: 20ce66e1a984
Revises: fbdfa90841a8
Create Date: 2026-09-24 16:40:41.766832

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20ce66e1a984"
down_revision: Union[str, Sequence[str], None] = "fbdfa90841a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aml_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "rule_type",
            sa.Enum(
                "CUSTOMER_RISK", "TRANSACTION", "VERIFICATION", name="aml_rule_type"
            ),
            nullable=False,
        ),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="aml_rule_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="aml_rule_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aml_rules_name"), "aml_rules", ["name"], unique=False)
    op.create_index(
        op.f("ix_aml_rules_rule_type"), "aml_rules", ["rule_type"], unique=False
    )
    op.create_index(
        op.f("ix_aml_rules_severity"), "aml_rules", ["severity"], unique=False
    )
    op.create_index(op.f("ix_aml_rules_status"), "aml_rules", ["status"], unique=False)

    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'AML_RULE_CREATED'")
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'AML_RULE_STATUS_CHANGED'"
    )
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'AML_RULE_EVALUATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_aml_rules_status"), table_name="aml_rules")
    op.drop_index(op.f("ix_aml_rules_severity"), table_name="aml_rules")
    op.drop_index(op.f("ix_aml_rules_rule_type"), table_name="aml_rules")
    op.drop_index(op.f("ix_aml_rules_name"), table_name="aml_rules")
    op.drop_table("aml_rules")
    # ### end Alembic commands ###
