# mypy: ignore-errors

"""add phone number to users

Revision ID: 27e64bc74516
Revises: 655b60ab47f7
Create Date: 2026-08-11 20:08:48.057033

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27e64bc74516"
down_revision: Union[str, Sequence[str], None] = "655b60ab47f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
