"""create customers table 2

Revision ID: 2b08ae77f7f4
Revises: f9a8cce0ac14
Create Date: 2026-08-31 18:28:10.916426

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2b08ae77f7f4"
down_revision: Union[str, Sequence[str], None] = "f9a8cce0ac14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
