# mypy: ignore-errors

"""add task management

Revision ID: 2f2805c9631f
Revises: 86665af4a6d6
Create Date: 2026-10-02 12:44:02.951023

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2805c9631f"
down_revision: Union[str, Sequence[str], None] = "86665af4a6d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audit_events = [
        "TASK_CREATED",
        "TASK_ASSIGNED",
        "TASK_UPDATED",
        "TASK_PRIORITY_CHANGED",
        "TASK_STATUS_CHANGED",
        "TASK_COMMENT_ADDED",
        "TASK_COMPLETED",
    ]

    for event in audit_events:
        op.execute(f"ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS '{event}'")

    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="task_priority"),
            server_default="MEDIUM",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="task_status",
            ),
            server_default="NEW",
            nullable=False,
        ),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workflow_execution_id", sa.UUID(), nullable=True),
        sa.Column("workflow_step_execution_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name="fk_tasks_assigned_to_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"], ["workflow_executions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_execution_id"],
            ["workflow_step_executions.id"],
            name="fk_tasks_workflow_step_execution",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_tasks",
        ),
    )
    op.create_index(
        op.f("ix_tasks_assigned_to"), "tasks", ["assigned_to"], unique=False
    )
    op.create_index(op.f("ix_tasks_due_date"), "tasks", ["due_date"], unique=False)
    op.create_index(op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_tasks_workflow_execution_id"),
        "tasks",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_workflow_step_execution_id"),
        "tasks",
        ["workflow_step_execution_id"],
        unique=False,
    )
    op.create_table(
        "task_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name="fk_task_comments_author_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name="fk_task_comments_task", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_task_comments",
        ),
    )
    op.create_index(
        op.f("ix_task_comments_author_id"), "task_comments", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_comments_created_at"),
        "task_comments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_comments_task_id"), "task_comments", ["task_id"], unique=False
    )
    op.create_table(
        "task_status_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW",
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="task_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW",
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="task_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name="fk_task_status_history_changed_by_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name="fk_task_status_history_task",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_task_status_history",
        ),
    )
    op.create_index(
        op.f("ix_task_status_history_changed_at"),
        "task_status_history",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_status_history_changed_by"),
        "task_status_history",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_status_history_task_id"),
        "task_status_history",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_task_status_history_task_id"), table_name="task_status_history"
    )
    op.drop_index(
        op.f("ix_task_status_history_changed_by"), table_name="task_status_history"
    )
    op.drop_index(
        op.f("ix_task_status_history_changed_at"), table_name="task_status_history"
    )
    op.drop_table("task_status_history")
    op.drop_index(op.f("ix_task_comments_task_id"), table_name="task_comments")
    op.drop_index(op.f("ix_task_comments_created_at"), table_name="task_comments")
    op.drop_index(op.f("ix_task_comments_author_id"), table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index(op.f("ix_tasks_workflow_step_execution_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_workflow_execution_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_date"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assigned_to"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
