"""add file metadata

Revision ID: 316ee703d4f9
Revises: 848981c493c2
Create Date: 2026-08-18 00:59:07.248481

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "316ee703d4f9"
down_revision: Union[str, Sequence[str], None] = "848981c493c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
