# mypy: ignore-errors

"""add organizations

Revision ID: 32b33c437946
Revises: 3648976d844a
Create Date: 2026-10-08 22:23:45.090577

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32b33c437946"
down_revision: Union[str, Sequence[str], None] = "3648976d844a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    organization_status = postgresql.ENUM(
        "ACTIVE",
        "SUSPENDED",
        "INACTIVE",
        name="organization_status",
        create_type=False,
    )

    organization_status.create(
        op.get_bind(),
        checkfirst=True,
    )

    op.create_table(
        "organizations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "legal_name",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "registration_number",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "tax_identification_number",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "industry",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "business_description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "contact_name",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "contact_email",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "contact_phone",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "website",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "country",
            sa.String(length=2),
            nullable=False,
        ),
        sa.Column(
            "status",
            organization_status,
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_organizations_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_organizations",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            name="uq_organizations_tenant_id",
        ),
    )

    op.create_index(
        "ix_organizations_status",
        "organizations",
        ["status"],
        unique=False,
    )

    op.alter_column(
        "report_exports", "requested_by", existing_type=sa.UUID(), nullable=True
    )
    op.create_index(
        op.f("ix_system_configurations_key"),
        "system_configurations",
        ["key"],
        unique=False,
    )
    op.drop_index(op.f("ix_tenants_code"), table_name="tenants")
    op.create_index(op.f("ix_tenants_code"), "tenants", ["code"], unique=True)
    op.create_index(
        op.f("ix_users_is_platform_admin"), "users", ["is_platform_admin"], unique=False
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'ORGANIZATION_CREATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'ORGANIZATION_UPDATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_platform_admin"), table_name="users")
    op.drop_index(op.f("ix_tenants_code"), table_name="tenants")
    op.create_index(op.f("ix_tenants_code"), "tenants", ["code"], unique=False)
    op.alter_column(
        "report_exports", "requested_by", existing_type=sa.UUID(), nullable=False
    )

    op.drop_index(
        "ix_organizations_status",
        table_name="organizations",
    )

    op.drop_table(
        "organizations",
    )

    sa.Enum(
        "ACTIVE",
        "SUSPENDED",
        "INACTIVE",
        name="organization_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
