# mypy: ignore-errors

"""update audit event type

Revision ID: 358977ad1ceb
Revises: 5c368a6107d9
Create Date: 2026-09-07 23:42:36.905095

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "358977ad1ceb"
down_revision: Union[str, Sequence[str], None] = "5c368a6107d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'CUSTOMER_DOCUMENT_CREATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
