# mypy: ignore-errors

"""create ai interaction logging

Revision ID: 4ca73b7161d8
Revises: 8f05c0a05b48
Create Date: 2026-09-16 20:11:16.453158

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ca73b7161d8"
down_revision: Union[str, Sequence[str], None] = "8f05c0a05b48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE ai_function ADD VALUE IF NOT EXISTS 'CASE_SUMMARY'")

    op.execute("ALTER TYPE ai_function ADD VALUE IF NOT EXISTS 'CUSTOMER_SUMMARY'")

    op.execute(
        "ALTER TYPE ai_function ADD VALUE IF NOT EXISTS 'DOCUMENT_REVIEW_SUMMARY'"
    )

    op.execute("ALTER TYPE ai_function ADD VALUE IF NOT EXISTS 'COMPLIANCE_NOTES'")

    op.create_table(
        "ai_interactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "ai_function",
            postgresql.ENUM(
                name="ai_function",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "CUSTOMER",
                "VERIFICATION_CASE",
                "DOCUMENT",
                name="ai_resource_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(), nullable=False),
        sa.Column("response_data", postgresql.JSONB(), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("provider_name", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "FAILED",
                name="ai_interaction_status",
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["prompt_id"], ["ai_prompts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_ai_interactions_ai_function"),
        "ai_interactions",
        ["ai_function"],
    )
    op.create_index(
        op.f("ix_ai_interactions_prompt_id"),
        "ai_interactions",
        ["prompt_id"],
    )
    op.create_index(
        op.f("ix_ai_interactions_resource_id"),
        "ai_interactions",
        ["resource_id"],
    )
    op.create_index(op.f("ix_ai_interactions_status"), "ai_interactions", ["status"])
    op.create_index(op.f("ix_ai_interactions_user_id"), "ai_interactions", ["user_id"])
    op.drop_index(
        op.f("ix_ai_prompt_assignments_ai_function"), table_name="ai_prompt_assignments"
    )
    op.create_index(
        op.f("ix_ai_prompt_assignments_ai_function"),
        "ai_prompt_assignments",
        ["ai_function"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ai_prompt_assignments_ai_function"), table_name="ai_prompt_assignments"
    )
    op.create_index(
        op.f("ix_ai_prompt_assignments_ai_function"),
        "ai_prompt_assignments",
        ["ai_function"],
        unique=False,
    )
    op.drop_index(op.f("ix_ai_interactions_user_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_status"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_resource_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_prompt_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_ai_function"), table_name="ai_interactions")
    op.drop_table("ai_interactions")
    op.execute("DROP TYPE IF EXISTS ai_interaction_status")
    op.execute("DROP TYPE IF EXISTS ai_resource_type")
    # ### end Alembic commands ###
