# mypy: ignore-errors

"""add compliance case workflow history

Revision ID: 4f11ac73ea60
Revises: 9883cbb9bbf7
Create Date: 2026-09-19 18:14:23.748767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f11ac73ea60"
down_revision: Union[str, Sequence[str], None] = "9883cbb9bbf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_case_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("compliance_case_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            postgresql.ENUM(
                "OPEN",
                "ASSIGNED",
                "UNDER_REVIEW",
                "ESCALATED",
                "RESOLVED",
                "CLOSED",
                name="compliance_case_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            postgresql.ENUM(
                "OPEN",
                "ASSIGNED",
                "UNDER_REVIEW",
                "ESCALATED",
                "RESOLVED",
                "CLOSED",
                name="compliance_case_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["compliance_case_id"], ["compliance_cases.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_case_history_changed_by"),
        "compliance_case_history",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_case_history_compliance_case_id"),
        "compliance_case_history",
        ["compliance_case_id"],
        unique=False,
    )
    op.add_column(
        "compliance_cases", sa.Column("resolution_reason", sa.Text(), nullable=True)
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'COMPLIANCE_CASE_ASSIGNED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'COMPLIANCE_CASE_STATUS_CHANGED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("compliance_cases", "resolution_reason")
    op.drop_index(
        op.f("ix_compliance_case_history_compliance_case_id"),
        table_name="compliance_case_history",
    )
    op.drop_index(
        op.f("ix_compliance_case_history_changed_by"),
        table_name="compliance_case_history",
    )
    op.drop_table("compliance_case_history")
    # ### end Alembic commands ###
