# mypy: ignore-errors

"""add investigation notes

Revision ID: 5ae81a081a39
Revises: cba232ccf8ce
Create Date: 2026-09-27 19:14:22.966360

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae81a081a39"
down_revision: Union[str, Sequence[str], None] = "cba232ccf8ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigation_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum("NOTE", "ACTION", "RESOLUTION", name="investigation_note_type"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("attachment_reference", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["identity_verification_cases.id"],
            name="fk_investigation_notes_case",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_investigation_notes_user",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigation_notes_activity_type"),
        "investigation_notes",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_notes_case_id"),
        "investigation_notes",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_notes_created_at"),
        "investigation_notes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_notes_user_id"),
        "investigation_notes",
        ["user_id"],
        unique=False,
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'INVESTIGATION_NOTE_CREATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_investigation_notes_user_id"), table_name="investigation_notes"
    )
    op.drop_index(
        op.f("ix_investigation_notes_created_at"), table_name="investigation_notes"
    )
    op.drop_index(
        op.f("ix_investigation_notes_case_id"), table_name="investigation_notes"
    )
    op.drop_index(
        op.f("ix_investigation_notes_activity_type"), table_name="investigation_notes"
    )
    op.drop_table("investigation_notes")
    # ### end Alembic commands ###
