# mypy: ignore-errors

"""add document unique type constraints

Revision ID: 5c368a6107d9
Revises: 624ac9fad6f4
Create Date: 2026-09-07 09:42:51.205886

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c368a6107d9"
down_revision: Union[str, Sequence[str], None] = "624ac9fad6f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'CUSTOMER_UPDATED'")

    op.create_unique_constraint(
        "uq_verification_document_types_name",
        "verification_document_types",
        ["name"],
    )

    op.create_index(
        "uq_identity_verification_cases_active_customer_type",
        "identity_verification_cases",
        ["customer_id", "verification_type"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('NOT_STARTED', 'PENDING', 'UNDER_REVIEW')"
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_verification_document_types_name",
        "verification_document_types",
        type_="unique",
    )

    op.drop_index(
        "uq_identity_verification_cases_active_customer_type",
        table_name="identity_verification_cases",
    )
    # ### end Alembic commands ###
