# mypy: ignore-errors

"""update audit event type

Revision ID: 5c76a20c0f01
Revises: ad7e6dddc346
Create Date: 2026-09-10 15:19:46.682631

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c76a20c0f01"
down_revision: Union[str, Sequence[str], None] = "ad7e6dddc346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'VERIFICATION_PROVIDER_REQUEST'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
