# mypy: ignore-errors

"""replace customer audit changed field with descriptive action

Revision ID: 5cc806eb4700
Revises: f37dce01abcb
Create Date: 2026-09-04 01:23:02.451796

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cc806eb4700"
down_revision: Union[str, Sequence[str], None] = "f37dce01abcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_audit_logs", "changed_field")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_audit_logs",
        sa.Column(
            "changed_field", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
