# mypy: ignore-errors

"""create customer documents

Revision ID: 624ac9fad6f4
Revises: 721648201720
Create Date: 2026-09-07 03:15:22.142952

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "624ac9fad6f4"
down_revision: Union[str, Sequence[str], None] = "721648201720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("verification_case_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("file_reference", sa.String(length=1000), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "VERIFIED",
                "REJECTED",
                "EXPIRED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["verification_document_types.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["identity_verification_cases.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_documents_customer_id"),
        "customer_documents",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_documents_document_type_id"),
        "customer_documents",
        ["document_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_documents_uploaded_by"),
        "customer_documents",
        ["uploaded_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_documents_verification_case_id"),
        "customer_documents",
        ["verification_case_id"],
        unique=False,
    )
    op.drop_index(
        op.f("uq_identity_verification_cases_active_customer_type"),
        table_name="identity_verification_cases",
        postgresql_where="(status = ANY (ARRAY['NOT_STARTED'::verificationstatus, "
        "'PENDING'::verificationstatus, 'UNDER_REVIEW'::verificationstatus]))",
    )
    op.drop_constraint(
        op.f("uq_verification_document_types_name"),
        "verification_document_types",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_verification_document_types_name"),
        table_name="verification_document_types",
    )
    op.create_index(
        op.f("ix_verification_document_types_name"),
        "verification_document_types",
        ["name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verification_document_types_name"),
        table_name="verification_document_types",
    )
    op.create_index(
        op.f("ix_verification_document_types_name"),
        "verification_document_types",
        ["name"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_verification_document_types_name"),
        "verification_document_types",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("uq_identity_verification_cases_active_customer_type"),
        "identity_verification_cases",
        ["customer_id", "verification_type"],
        unique=True,
        postgresql_where="(status = ANY (ARRAY['NOT_STARTED'::verificationstatus, "
        "'PENDING'::verificationstatus, 'UNDER_REVIEW'::verificationstatus]))",
    )
    op.drop_index(
        op.f("ix_customer_documents_verification_case_id"),
        table_name="customer_documents",
    )
    op.drop_index(
        op.f("ix_customer_documents_uploaded_by"), table_name="customer_documents"
    )
    op.drop_index(
        op.f("ix_customer_documents_document_type_id"), table_name="customer_documents"
    )
    op.drop_index(
        op.f("ix_customer_documents_customer_id"), table_name="customer_documents"
    )
    op.drop_table("customer_documents")
    # ### end Alembic commands ###
