# mypy: ignore-errors

"""add is_deleted to users

Revision ID: 655b60ab47f7
Revises: 9112c50d60c7
Create Date: 2026-08-09 23:29:45.646777

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "655b60ab47f7"
down_revision: Union[str, Sequence[str], None] = "9112c50d60c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
