# mypy: ignore-errors

"""add system configurations

Revision ID: 675474191112
Revises: 6f0254b4f413
Create Date: 2026-10-03 20:26:28.209227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "675474191112"
down_revision: Union[str, Sequence[str], None] = "6f0254b4f413"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "WORKFLOW",
                "NOTIFICATION_TEMPLATE",
                "SLA",
                "RISK",
                "DOCUMENT",
                name="system_configuration_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="system_configuration_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "key",
            name="uq_system_configurations_key",
        ),
    )
    op.create_index(
        op.f("ix_system_configurations_category"),
        "system_configurations",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_configurations_key"),
        "system_configurations",
        ["key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_system_configurations_status"),
        "system_configurations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_configurations_updated_by"),
        "system_configurations",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_status_created",
        "notifications",
        ["user_id", "status", "created_at"],
        unique=False,
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'SYSTEM_CONFIGURATION_CREATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'SYSTEM_CONFIGURATION_UPDATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'SYSTEM_CONFIGURATION_STATUS_CHANGED'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_user_status_created", table_name="notifications")
    op.drop_index(
        op.f("ix_system_configurations_updated_by"), table_name="system_configurations"
    )
    op.drop_index(
        op.f("ix_system_configurations_status"), table_name="system_configurations"
    )
    op.drop_index(
        op.f("ix_system_configurations_key"), table_name="system_configurations"
    )
    op.drop_index(
        op.f("ix_system_configurations_category"), table_name="system_configurations"
    )
    op.drop_table("system_configurations")
    # ### end Alembic commands ###
