# mypy: ignore-errors

"""add customer risk profiles

Revision ID: 6a91a0cf614c
Revises: 4f11ac73ea60
Create Date: 2026-09-20 19:45:03.676413

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a91a0cf614c"
down_revision: Union[str, Sequence[str], None] = "4f11ac73ea60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_risk_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="customer_risk_level"),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_category", sa.String(length=100), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assessment_source", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", name="uq_customer_risk_profiles_customer_id"
        ),
    )
    op.create_index(
        op.f("ix_customer_risk_profiles_customer_id"),
        "customer_risk_profiles",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_risk_profiles_risk_level"),
        "customer_risk_profiles",
        ["risk_level"],
        unique=False,
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'CUSTOMER_RISK_PROFILE_CREATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'CUSTOMER_RISK_PROFILE_UPDATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_risk_profiles_risk_level"),
        table_name="customer_risk_profiles",
    )
    op.drop_index(
        op.f("ix_customer_risk_profiles_customer_id"),
        table_name="customer_risk_profiles",
    )
    op.drop_table("customer_risk_profiles")
    # ### end Alembic commands ###
