# mypy: ignore-errors

"""add operations dashboard indexes

Revision ID: 6f0254b4f413
Revises: 87a5892599ea
Create Date: 2026-10-03 19:16:42.143428

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f0254b4f413"
down_revision: Union[str, Sequence[str], None] = "87a5892599ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notifications_user_status_created"), table_name="notifications"
    )
    op.create_index(
        "ix_customers_created_at",
        "customers",
        ["created_at"],
    )

    op.create_index(
        "ix_customers_country_of_residence",
        "customers",
        ["country_of_residence"],
    )

    op.create_index(
        "ix_users_role",
        "users",
        ["role"],
    )

    op.create_index(
        "ix_workflow_executions_started_at",
        "workflow_executions",
        ["started_at"],
    )

    op.create_index(
        "ix_tasks_created_at",
        "tasks",
        ["created_at"],
    )

    op.create_index(
        "ix_compliance_cases_created_at",
        "compliance_cases",
        ["created_at"],
    )

    op.create_index(
        "ix_identity_verification_cases_created_at",
        "identity_verification_cases",
        ["created_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_notifications_user_status_created"),
        "notifications",
        ["user_id", "status", "created_at"],
        unique=False,
    )
    op.drop_index(
        "ix_identity_verification_cases_created_at",
        table_name="identity_verification_cases",
    )

    op.drop_index(
        "ix_compliance_cases_created_at",
        table_name="compliance_cases",
    )

    op.drop_index(
        "ix_tasks_due_date",
        table_name="tasks",
    )

    op.drop_index(
        "ix_tasks_created_at",
        table_name="tasks",
    )

    op.drop_index(
        "ix_workflow_executions_started_at",
        table_name="workflow_executions",
    )

    op.drop_index(
        "ix_users_role",
        table_name="users",
    )

    op.drop_index(
        "ix_customers_country_of_residence",
        table_name="customers",
    )

    op.drop_index(
        "ix_customers_created_at",
        table_name="customers",
    )
    # ### end Alembic commands ###
