# mypy: ignore_errors

"""update audit event type

Revision ID: 74375a56be61
Revises: d6742451f605
Create Date: 2026-09-03 02:32:37.100094

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74375a56be61"
down_revision: Union[str, Sequence[str], None] = "d6742451f605"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'ACCESS_DENIED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
