# mypy: ignore-errors

"""add created_at server default

Revision ID: 75c624f2b0fb
Revises: b5b256f66283
Create Date: 2026-09-02 00:24:36.298882

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75c624f2b0fb"
down_revision: Union[str, Sequence[str], None] = "b5b256f66283"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "customers",
        "created_at",
        server_default=sa.text("now()"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
