# mypy: ignore-errors

"""add workflow audit logs

Revision ID: 7df5d6f5f78a
Revises: 675474191112
Create Date: 2026-10-04 15:06:23.879300

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7df5d6f5f78a"
down_revision: Union[str, Sequence[str], None] = "675474191112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("step_name", sa.String(length=200), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("old_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflow_executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_audit_logs_action"),
        "workflow_audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_audit_logs_created_at"),
        "workflow_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_audit_logs_user_id",
        "workflow_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_audit_logs_workflow_created",
        "workflow_audit_logs",
        ["workflow_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_audit_logs_workflow_id"),
        "workflow_audit_logs",
        ["workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_audit_logs_workflow_id"), table_name="workflow_audit_logs"
    )
    op.drop_index(
        "ix_workflow_audit_logs_workflow_created", table_name="workflow_audit_logs"
    )
    op.drop_index("ix_workflow_audit_logs_user_id", table_name="workflow_audit_logs")
    op.drop_index(
        op.f("ix_workflow_audit_logs_created_at"), table_name="workflow_audit_logs"
    )
    op.drop_index(
        op.f("ix_workflow_audit_logs_action"), table_name="workflow_audit_logs"
    )
    op.drop_table("workflow_audit_logs")
    # ### end Alembic commands ###
