"""update enum types 2

Revision ID: 85b9a8e48d1f
Revises: f8a343441b4b
Create Date: 2026-09-01 16:52:16.773551

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "85b9a8e48d1f"
down_revision: Union[str, Sequence[str], None] = "f8a343441b4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
