# mypy: ignore-errors

"""add sla tracking

Revision ID: 87a5892599ea
Revises: 9719652ee6c2
Create Date: 2026-10-03 17:28:55.449393

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87a5892599ea"
down_revision: Union[str, Sequence[str], None] = "9719652ee6c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


sla_status_enum = postgresql.ENUM(
    "WITHIN_SLA",
    "APPROACHING_DEADLINE",
    "BREACHED",
    "COMPLETED",
    name="sla_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()

    sla_status_enum.create(
        connection,
        checkfirst=True,
    )

    op.add_column(
        "tasks", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("tasks", sa.Column("sla_status", sla_status_enum, nullable=True))
    op.create_index(op.f("ix_tasks_sla_status"), "tasks", ["sla_status"], unique=False)
    op.add_column(
        "workflow_executions",
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workflow_executions", sa.Column("sla_status", sla_status_enum, nullable=True)
    )
    op.create_index(
        op.f("ix_workflow_executions_due_date"),
        "workflow_executions",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_sla_status"),
        "workflow_executions",
        ["sla_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_executions_sla_status"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_due_date"), table_name="workflow_executions"
    )
    op.drop_column("workflow_executions", "sla_status")
    op.drop_column("workflow_executions", "due_date")
    op.drop_index(op.f("ix_tasks_sla_status"), table_name="tasks")
    op.drop_column("tasks", "sla_status")
    op.drop_column("tasks", "completed_at")

    sla_status_enum.drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
