# mypy: ignore-errors

"""create analytics snapshot tables

Revision ID: 8a3b570b7e25
Revises: 7df5d6f5f78a
Create Date: 2026-10-04 16:14:28.989839

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a3b570b7e25"
down_revision: Union[str, Sequence[str], None] = "7df5d6f5f78a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_compliance_daily",
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("total_cases", sa.Integer(), nullable=False),
        sa.Column("open_cases", sa.Integer(), nullable=False),
        sa.Column("resolved_cases", sa.Integer(), nullable=False),
        sa.Column("closed_cases", sa.Integer(), nullable=False),
        sa.Column("total_alerts", sa.Integer(), nullable=False),
        sa.Column("low_severity_alerts", sa.Integer(), nullable=False),
        sa.Column("medium_severity_alerts", sa.Integer(), nullable=False),
        sa.Column("high_severity_alerts", sa.Integer(), nullable=False),
        sa.Column("critical_severity_alerts", sa.Integer(), nullable=False),
        sa.Column("low_risk_customers", sa.Integer(), nullable=False),
        sa.Column("medium_risk_customers", sa.Integer(), nullable=False),
        sa.Column("high_risk_customers", sa.Integer(), nullable=False),
        sa.Column("critical_risk_customers", sa.Integer(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_date",
            name="pk_analytics_compliance_daily",
        ),
    )
    op.create_table(
        "analytics_customer_daily",
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("total_customers", sa.Integer(), nullable=False),
        sa.Column("new_registrations", sa.Integer(), nullable=False),
        sa.Column("pending_verification", sa.Integer(), nullable=False),
        sa.Column("verified_customers", sa.Integer(), nullable=False),
        sa.Column("suspended_customers", sa.Integer(), nullable=False),
        sa.Column("rejected_customers", sa.Integer(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("snapshot_date"),
    )
    op.create_table(
        "analytics_operations_daily",
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("open_tasks", sa.Integer(), nullable=False),
        sa.Column("completed_tasks", sa.Integer(), nullable=False),
        sa.Column("overdue_tasks", sa.Integer(), nullable=False),
        sa.Column("task_sla_within_sla", sa.Integer(), nullable=False),
        sa.Column("task_sla_approaching_deadline", sa.Integer(), nullable=False),
        sa.Column("task_sla_breached", sa.Integer(), nullable=False),
        sa.Column("task_sla_completed", sa.Integer(), nullable=False),
        sa.Column("total_workflows", sa.Integer(), nullable=False),
        sa.Column("active_workflows", sa.Integer(), nullable=False),
        sa.Column("completed_workflows", sa.Integer(), nullable=False),
        sa.Column("failed_workflows", sa.Integer(), nullable=False),
        sa.Column("workflow_sla_within_sla", sa.Integer(), nullable=False),
        sa.Column("workflow_sla_approaching_deadline", sa.Integer(), nullable=False),
        sa.Column("workflow_sla_breached", sa.Integer(), nullable=False),
        sa.Column("workflow_sla_completed", sa.Integer(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_date",
            name="pk_analytics_operations_daily",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analytics_operations_daily")
    op.drop_table("analytics_customer_daily")
    op.drop_table("analytics_compliance_daily")
    # ### end Alembic commands ###
