"""add file storage table

Revision ID: 971553f9b572
Revises: 316ee703d4f9
Create Date: 2026-08-18 01:03:00.952710

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "971553f9b572"
down_revision: Union[str, Sequence[str], None] = "316ee703d4f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
