# mypy: ignore-errors

"""add communication logs

Revision ID: 9719652ee6c2
Revises: 968df83f2bbb
Create Date: 2026-10-03 16:26:59.272196

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9719652ee6c2"
down_revision: Union[str, Sequence[str], None] = "968df83f2bbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communication_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "SMS", name="communication_channel"),
            nullable=False,
        ),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "SENT", "DELIVERED", "FAILED", name="communication_status"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_communication_logs_channel"),
        "communication_logs",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_communication_logs_recipient"),
        "communication_logs",
        ["recipient"],
        unique=False,
    )
    op.create_index(
        op.f("ix_communication_logs_status"),
        "communication_logs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_communication_logs_template_id"),
        "communication_logs",
        ["template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_communication_logs_template_id"), table_name="communication_logs"
    )
    op.drop_index(op.f("ix_communication_logs_status"), table_name="communication_logs")
    op.drop_index(
        op.f("ix_communication_logs_recipient"), table_name="communication_logs"
    )
    op.drop_index(
        op.f("ix_communication_logs_channel"), table_name="communication_logs"
    )
    op.drop_table("communication_logs")
    # ### end Alembic commands ###
