# mypy: ignore-errors

"""create compliance cases

Revision ID: 9883cbb9bbf7
Revises: 37ee116c930d
Create Date: 2026-09-19 16:37:07.015330

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9883cbb9bbf7"
down_revision: Union[str, Sequence[str], None] = "37ee116c930d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "case_type",
            sa.Enum(
                "CUSTOMER_REVIEW",
                "AML_ALERT",
                "VERIFICATION_ISSUE",
                "SUSPICIOUS_ACTIVITY_REVIEW",
                "MANUAL_INVESTIGATION",
                name="compliance_case_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", "CRITICAL", name="compliance_case_priority"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "ASSIGNED",
                "UNDER_REVIEW",
                "ESCALATED",
                "RESOLVED",
                "CLOSED",
                name="compliance_case_status",
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_cases_assigned_to"),
        "compliance_cases",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_cases_case_type"),
        "compliance_cases",
        ["case_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_cases_customer_id"),
        "compliance_cases",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_cases_priority"),
        "compliance_cases",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_cases_status"), "compliance_cases", ["status"], unique=False
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'COMPLIANCE_CASE_CREATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'COMPLIANCE_CASE_UPDATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_compliance_cases_status"), table_name="compliance_cases")
    op.drop_index(op.f("ix_compliance_cases_priority"), table_name="compliance_cases")
    op.drop_index(
        op.f("ix_compliance_cases_customer_id"), table_name="compliance_cases"
    )
    op.drop_index(op.f("ix_compliance_cases_case_type"), table_name="compliance_cases")
    op.drop_index(
        op.f("ix_compliance_cases_assigned_to"), table_name="compliance_cases"
    )
    op.drop_table("compliance_cases")
    # ### end Alembic commands ###
