# mypy: ignore-errors

"""create partial unique verification cases

Revision ID: 9aed960c9a57
Revises: a3abb85b3545
Create Date: 2026-09-06 13:24:31.904648

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aed960c9a57"
down_revision: Union[str, Sequence[str], None] = "a3abb85b3545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_identity_verification_cases_active_customer_type",
        "identity_verification_cases",
        ["customer_id", "verification_type"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('NOT_STARTED', 'PENDING', 'UNDER_REVIEW')"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_identity_verification_cases_active_customer",
        table_name="identity_verification_cases",
    )
    # ### end Alembic commands ###
