"""Initial migration

Revision ID: 9b2e22030c10
Revises:
Create Date: 2026-08-05 13:29:46.869252

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9b2e22030c10"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
