# mypy: ignore-errors

"""update audit event type 2

Revision ID: a3abb85b3545
Revises: b0ac0bf47998
Create Date: 2026-09-05 20:12:19.599353

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3abb85b3545"
down_revision: Union[str, Sequence[str], None] = "b0ac0bf47998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'VERIFICATION_CASE_STATUS_CHANGED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
