# mypy: ignore-errors

"""create document extractions

Revision ID: aa079d8e4e34
Revises: 1ac1b4bd68c2
Create Date: 2026-09-14 07:48:59.304000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa079d8e4e34"
down_revision: Union[str, Sequence[str], None] = "1ac1b4bd68c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_extractions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ocr_result_id", sa.UUID(), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="extraction_status",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("document_number", sa.String(length=100), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["customer_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"], ["ocr_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_extractions_document_id"),
        "document_extractions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extractions_ocr_result_id"),
        "document_extractions",
        ["ocr_result_id"],
        unique=False,
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'DOCUMENT_EXTRACTION_REQUESTED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'DOCUMENT_EXTRACTION_COMPLETED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'DOCUMENT_EXTRACTION_FAILED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_extractions_ocr_result_id"), table_name="document_extractions"
    )
    op.drop_index(
        op.f("ix_document_extractions_document_id"), table_name="document_extractions"
    )
    op.drop_table("document_extractions")
    # ### end Alembic commands ###
