"""update Schemas

Revision ID: abba92bf21e9
Revises: 06eed7cb035f
Create Date: 2026-08-31 20:12:55.864676

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "abba92bf21e9"
down_revision: Union[str, Sequence[str], None] = "06eed7cb035f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
