# mypy: ignore_errors

"""add compliance reporting history support

Revision ID: ac5dd5cea7f5
Revises: 5ae81a081a39
Create Date: 2026-09-27 20:12:35.007135

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac5dd5cea7f5"
down_revision: Union[str, Sequence[str], None] = "5ae81a081a39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_risk_assessment_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "risk_level",
            postgresql.ENUM(
                name="customer_risk_level",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_category", sa.String(length=100), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assessment_source", sa.String(length=100), nullable=False),
        sa.Column(
            "calculation_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name="fk_customer_risk_history_customer",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_risk_assessment_history_assessed_at"),
        "customer_risk_assessment_history",
        ["assessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_risk_assessment_history_customer_id"),
        "customer_risk_assessment_history",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_risk_assessment_history_risk_level"),
        "customer_risk_assessment_history",
        ["risk_level"],
        unique=False,
    )
    op.add_column(
        "transaction_monitoring_results",
        sa.Column("country", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_transaction_monitoring_results_country"),
        "transaction_monitoring_results",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_monitoring_results_created_at"),
        "transaction_monitoring_results",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transaction_monitoring_results_created_at"),
        table_name="transaction_monitoring_results",
    )
    op.drop_index(
        op.f("ix_transaction_monitoring_results_country"),
        table_name="transaction_monitoring_results",
    )
    op.drop_column("transaction_monitoring_results", "country")
    op.drop_index(
        op.f("ix_customer_risk_assessment_history_risk_level"),
        table_name="customer_risk_assessment_history",
    )
    op.drop_index(
        op.f("ix_customer_risk_assessment_history_customer_id"),
        table_name="customer_risk_assessment_history",
    )
    op.drop_index(
        op.f("ix_customer_risk_assessment_history_assessed_at"),
        table_name="customer_risk_assessment_history",
    )
    op.drop_table("customer_risk_assessment_history")
    # ### end Alembic commands ###
