# mypy: ignore-errors

"""create verification reviews

Revision ID: ad7e6dddc346
Revises: 358977ad1ceb
Create Date: 2026-09-10 03:43:59.370694

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad7e6dddc346"
down_revision: Union[str, Sequence[str], None] = "358977ad1ceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("verification_case_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVE", "REJECT", "REQUEST_MORE_INFORMATION", name="review_decision"
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["identity_verification_cases.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_reviews_reviewer_id"),
        "verification_reviews",
        ["reviewer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_reviews_verification_case_id"),
        "verification_reviews",
        ["verification_case_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verification_reviews_verification_case_id"),
        table_name="verification_reviews",
    )
    op.drop_index(
        op.f("ix_verification_reviews_reviewer_id"), table_name="verification_reviews"
    )
    op.drop_table("verification_reviews")
    # ### end Alembic commands ###
