# mypy: ignore-errors

"""update audit event type

Revision ID: b0ac0bf47998
Revises: c9807d8f7464
Create Date: 2026-09-05 18:02:10.003397

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0ac0bf47998"
down_revision: Union[str, Sequence[str], None] = "c9807d8f7464"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'VERIFICATION_CASE_CREATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
