# mypy: ignore-errors

"""add document extraction review logs

Revision ID: b5329a6efd85
Revises: f1db270b5c87
Create Date: 2026-09-14 19:29:13.216124

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5329a6efd85"
down_revision: Union[str, Sequence[str], None] = "f1db270b5c87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_extraction_review_logs",
        sa.Column("id", sa.UUID(), primary_key=True, nullable=False),
        sa.Column("document_extraction_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_extraction_id"], ["document_extractions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_extraction_review_logs_document_extraction_id"),
        "document_extraction_review_logs",
        ["document_extraction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extraction_review_logs_reviewer_id"),
        "document_extraction_review_logs",
        ["reviewer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_extraction_review_logs_reviewer_id"),
        table_name="document_extraction_review_logs",
    )
    op.drop_index(
        op.f("ix_document_extraction_review_logs_document_extraction_id"),
        table_name="document_extraction_review_logs",
    )
    op.drop_table("document_extraction_review_logs")
    # ### end Alembic commands ###
