# mypy: ignore-errors

"""create knowledge documents

Revision ID: be362e345cfe
Revises: 4ca73b7161d8
Create Date: 2026-09-17 13:01:01.930441

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be362e345cfe"
down_revision: Union[str, Sequence[str], None] = "4ca73b7161d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("file_reference", sa.String(length=1000), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                name="knowledge_document_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_uploaded_by"),
        "knowledge_documents",
        ["uploaded_by"],
        unique=False,
    )

    op.create_unique_constraint(
        "uq_knowledge_documents_name_version",
        "knowledge_documents",
        ["name", "version"],
    )

    op.create_index(
        "uq_knowledge_documents_active_name",
        "knowledge_documents",
        ["name"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_knowledge_documents_active_name",
        table_name="knowledge_documents",
    )

    op.drop_constraint(
        "uq_knowledge_documents_name_version",
        "knowledge_documents",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_knowledge_documents_uploaded_by"), table_name="knowledge_documents"
    )
    op.drop_table("knowledge_documents")
    # ### end Alembic commands ###
