# mypy: ignore-errors

"""create identity verification cases

Revision ID: c9807d8f7464
Revises: 5cc806eb4700
Create Date: 2026-09-05 17:42:48.008603

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9807d8f7464"
down_revision: Union[str, Sequence[str], None] = "5cc806eb4700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_verification_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "verification_type",
            sa.Enum("IDENTITY", "ADDRESS", "BUSINESS", name="verificationtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "PENDING",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="verificationstatus",
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_identity_verification_cases_assigned_to"),
        "identity_verification_cases",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_verification_cases_customer_id"),
        "identity_verification_cases",
        ["customer_id"],
        unique=False,
    )
    op.alter_column(
        "customer_audit_logs",
        "action",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer_audit_logs",
        "action",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_identity_verification_cases_customer_id"),
        table_name="identity_verification_cases",
    )
    op.drop_index(
        op.f("ix_identity_verification_cases_assigned_to"),
        table_name="identity_verification_cases",
    )
    op.drop_table("identity_verification_cases")
    # ### end Alembic commands ###
