# mypy: ignore-errors

"""add verification case assignment tracking

Revision ID: cba232ccf8ce
Revises: 1cb2d9ac4591
Create Date: 2026-09-27 16:14:07.501580

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cba232ccf8ce"
down_revision: Union[str, Sequence[str], None] = "1cb2d9ac4591"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_case_assignment_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("verification_case_id", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=False),
        sa.Column("previous_reviewer", sa.UUID(), nullable=True),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name="fk_assignment_history_assigned_by",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name="fk_assignment_history_assigned_to",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_reviewer"],
            ["users.id"],
            name="fk_assignment_history_previous_reviewer",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verification_case_id"],
            ["identity_verification_cases.id"],
            name="fk_assignment_history_case",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_case_assignment_history_assigned_at"),
        "verification_case_assignment_history",
        ["assigned_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_case_assignment_history_assigned_by"),
        "verification_case_assignment_history",
        ["assigned_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_case_assignment_history_assigned_to"),
        "verification_case_assignment_history",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_case_assignment_history_previous_reviewer"),
        "verification_case_assignment_history",
        ["previous_reviewer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_case_assignment_history_verification_case_id"),
        "verification_case_assignment_history",
        ["verification_case_id"],
        unique=False,
    )
    op.add_column(
        "identity_verification_cases",
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "identity_verification_cases",
        sa.Column("assigned_by", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_identity_verification_cases_assigned_by_users",
        "identity_verification_cases",
        "users",
        ["assigned_by"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_index(
        "ix_identity_verification_cases_assigned_at",
        "identity_verification_cases",
        ["assigned_at"],
    )

    op.create_index(
        "ix_identity_verification_cases_assigned_by",
        "identity_verification_cases",
        ["assigned_by"],
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'VERIFICATION_CASE_ASSIGNED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_identity_verification_cases_assigned_by_users",
        "identity_verification_cases",
        type_="foreignkey",
    )
    op.drop_column("identity_verification_cases", "assigned_by")
    op.drop_column("identity_verification_cases", "assigned_at")
    op.drop_index(
        "ix_identity_verification_cases_assigned_by",
        table_name="identity_verification_cases",
    )

    op.drop_index(
        "ix_identity_verification_cases_assigned_at",
        table_name="identity_verification_cases",
    )
    op.drop_index(
        op.f("ix_verification_case_assignment_history_verification_case_id"),
        table_name="verification_case_assignment_history",
    )
    op.drop_index(
        op.f("ix_verification_case_assignment_history_previous_reviewer"),
        table_name="verification_case_assignment_history",
    )
    op.drop_index(
        op.f("ix_verification_case_assignment_history_assigned_to"),
        table_name="verification_case_assignment_history",
    )
    op.drop_index(
        op.f("ix_verification_case_assignment_history_assigned_by"),
        table_name="verification_case_assignment_history",
    )
    op.drop_index(
        op.f("ix_verification_case_assignment_history_assigned_at"),
        table_name="verification_case_assignment_history",
    )
    op.drop_table("verification_case_assignment_history")
    # ### end Alembic commands ###
