# mypy: ignore-errors

"""add extraction review workflow and split names

Revision ID: d3ad739be233
Revises: b5329a6efd85
Create Date: 2026-09-14 20:43:33.956428

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3ad739be233"
down_revision: Union[str, Sequence[str], None] = "b5329a6efd85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_extractions",
        sa.Column("first_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("middle_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("last_name", sa.String(length=100), nullable=True),
    )
    op.drop_column("document_extractions", "full_name")
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'DOCUMENT_EXTRACTION_REVIEW_UPDATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'DOCUMENT_EXTRACTION_REVIEW_APPROVED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'DOCUMENT_EXTRACTION_REVIEW_REJECTED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_extractions",
        sa.Column(
            "full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("document_extractions", "last_name")
    op.drop_column("document_extractions", "middle_name")
    op.drop_column("document_extractions", "first_name")
    # ### end Alembic commands ###
