# mypy: ignore-errors

"""create customer audit logs

Revision ID: d6742451f605
Revises: 117d493767de
Create Date: 2026-09-03 00:10:35.209181

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6742451f605"
down_revision: Union[str, Sequence[str], None] = "117d493767de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("changed_field", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_audit_logs_customer_id"),
        "customer_audit_logs",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_audit_logs_user_id"),
        "customer_audit_logs",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_audit_logs_user_id"), table_name="customer_audit_logs"
    )
    op.drop_index(
        op.f("ix_customer_audit_logs_customer_id"), table_name="customer_audit_logs"
    )
    op.drop_table("customer_audit_logs")
    # ### end Alembic commands ###
