# mypy: ignore_errors

"""add configurable workflow engine

Revision ID: d705b42a9aa9
Revises: ac5dd5cea7f5
Create Date: 2026-10-01 17:36:42.704714

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d705b42a9aa9"
down_revision: Union[str, Sequence[str], None] = "ac5dd5cea7f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "INACTIVE", name="workflow_status"),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_workflows_name"),
    )
    op.create_index(op.f("ix_workflows_name"), "workflows", ["name"], unique=False)
    op.create_index(op.f("ix_workflows_status"), "workflows", ["status"], unique=False)
    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("assigned_role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_id", "order_number", name="uq_workflow_steps_workflow_order"
        ),
    )
    op.create_index(
        op.f("ix_workflow_steps_workflow_id"),
        "workflow_steps",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "workflow_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                "FAILED",
                name="workflow_execution_status",
            ),
            server_default="IN_PROGRESS",
            nullable=False,
        ),
        sa.Column("current_step_id", sa.UUID(), nullable=True),
        sa.Column("started_by", sa.UUID(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_step_id"], ["workflow_steps.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["started_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_executions_current_step_id"),
        "workflow_executions",
        ["current_step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_entity_id"),
        "workflow_executions",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_entity_type"),
        "workflow_executions",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_started_by"),
        "workflow_executions",
        ["started_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_status"),
        "workflow_executions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_workflow_id"),
        "workflow_executions",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "workflow_step_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("workflow_step_id", sa.UUID(), nullable=False),
        sa.Column("step_name", sa.String(length=200), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("assigned_role", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "SKIPPED",
                name="workflow_step_execution_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"], ["workflow_executions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["workflow_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_execution_id",
            "workflow_step_id",
            name="uq_workflow_step_execution",
        ),
    )
    op.create_index(
        op.f("ix_workflow_step_executions_status"),
        "workflow_step_executions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_step_executions_workflow_execution_id"),
        "workflow_step_executions",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_step_executions_workflow_step_id"),
        "workflow_step_executions",
        ["workflow_step_id"],
        unique=False,
    )

    audit_events = [
        "WORKFLOW_CREATED",
        "WORKFLOW_UPDATED",
        "WORKFLOW_STATUS_CHANGED",
        "WORKFLOW_STEP_CREATED",
        "WORKFLOW_STEP_UPDATED",
        "WORKFLOW_STEP_DELETED",
        "WORKFLOW_EXECUTION_STARTED",
        "WORKFLOW_STEP_COMPLETED",
        "WORKFLOW_EXECUTION_COMPLETED",
        "WORKFLOW_EXECUTION_CANCELLED",
    ]

    for event in audit_events:
        op.execute(f"ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS '{event}'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_step_executions_workflow_step_id"),
        table_name="workflow_step_executions",
    )
    op.drop_index(
        op.f("ix_workflow_step_executions_workflow_execution_id"),
        table_name="workflow_step_executions",
    )
    op.drop_index(
        op.f("ix_workflow_step_executions_status"),
        table_name="workflow_step_executions",
    )
    op.drop_table("workflow_step_executions")
    op.drop_index(
        op.f("ix_workflow_executions_workflow_id"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_status"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_started_by"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_entity_type"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_entity_id"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_current_step_id"), table_name="workflow_executions"
    )
    op.drop_table("workflow_executions")
    op.drop_index(op.f("ix_workflow_steps_workflow_id"), table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index(op.f("ix_workflows_status"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_name"), table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
