# mypy: ignore-errors

"""add customer history table

Revision ID: dfa8ef64bada
Revises: abba92bf21e9
Create Date: 2026-08-31 21:32:08.220987

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfa8ef64bada"
down_revision: Union[str, Sequence[str], None] = "abba92bf21e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers",
        "status",
        existing_type=postgresql.ENUM("ACTIVE", "INACTIVE", name="customer_status"),
        type_=sa.Enum(
            "NEW",
            "PENDING_VERIFICATION",
            "VERIFIED",
            "SUSPENDED",
            "REJECTED",
            name="customer_status",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers",
        "status",
        existing_type=sa.Enum(
            "NEW",
            "PENDING_VERIFICATION",
            "VERIFIED",
            "SUSPENDED",
            "REJECTED",
            name="customer_status",
        ),
        type_=postgresql.ENUM("ACTIVE", "INACTIVE", name="customer_status"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
