"""create customers table 4

Revision ID: e077a89460fd
Revises: 21a7bdc6b4a8
Create Date: 2026-08-31 19:06:00.091441

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e077a89460fd"
down_revision: Union[str, Sequence[str], None] = "21a7bdc6b4a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
