# mypy: ignore_errors

"""add extraction review workflow

Revision ID: f1db270b5c87
Revises: aa079d8e4e34
Create Date: 2026-09-14 19:06:17.553285

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1db270b5c87"
down_revision: Union[str, Sequence[str], None] = "aa079d8e4e34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    extraction_review_status = postgresql.ENUM(
        "PENDING_REVIEW",
        "APPROVED",
        "REJECTED",
        name="extraction_review_status",
    )

    extraction_review_status.create(
        op.get_bind(),
        checkfirst=True,
    )
    op.add_column(
        "document_extractions",
        sa.Column(
            "review_status",
            extraction_review_status,
            nullable=False,
            server_default="PENDING_REVIEW",
        ),
    )
    op.add_column(
        "document_extractions",
        sa.Column("reviewed_by", sa.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "document_extractions",
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "document_extractions", sa.Column("rejection_reason", sa.Text(), nullable=True)
    )
    op.create_index(
        op.f("ix_document_extractions_reviewed_by"),
        "document_extractions",
        ["reviewed_by"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_document_extractions_reviewed_by_users",
        "document_extractions",
        "users",
        ["reviewed_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "document_extractions",
        "review_status",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document_extractions", type_="foreignkey")
    op.drop_index(
        op.f("ix_document_extractions_reviewed_by"), table_name="document_extractions"
    )
    op.drop_column("document_extractions", "rejection_reason")
    op.drop_column("document_extractions", "reviewed_at")
    op.drop_column("document_extractions", "reviewed_by")
    op.drop_column("document_extractions", "review_status")
    # ### end Alembic commands ###
