# mypy: ignore-errors

"""add resource fields to customer audit logs

Revision ID: f37dce01abcb
Revises: 74375a56be61
Create Date: 2026-09-03 03:22:27.657101

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f37dce01abcb"
down_revision: Union[str, Sequence[str], None] = "74375a56be61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_audit_logs",
        sa.Column("resource_type", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "customer_audit_logs", sa.Column("resource_id", sa.UUID(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_audit_logs", "resource_id")
    op.drop_column("customer_audit_logs", "resource_type")
    # ### end Alembic commands ###
