"""create customers table

Revision ID: f9a8cce0ac14
Revises: de392fd403a5
Create Date: 2026-08-31 18:15:39.106114

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f9a8cce0ac14"
down_revision: Union[str, Sequence[str], None] = "de392fd403a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
