# mypy: ignore-errors

"""add configurable risk scoring

Revision ID: fbdfa90841a8
Revises: 6a91a0cf614c
Create Date: 2026-09-21 22:29:57.439479

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbdfa90841a8"
down_revision: Union[str, Sequence[str], None] = "6a91a0cf614c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_risk_profiles",
        sa.Column(
            "calculation_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )

    op.create_table(
        "risk_score_thresholds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "risk_level",
            postgresql.ENUM(
                name="customer_risk_level",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("risk_level", name="uq_risk_score_thresholds_risk_level"),
    )
    op.create_index(
        op.f("ix_risk_score_thresholds_is_active"),
        "risk_score_thresholds",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_score_thresholds_risk_level"),
        "risk_score_thresholds",
        ["risk_level"],
        unique=False,
    )
    op.create_table(
        "risk_scoring_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("factor_key", sa.String(length=100), nullable=False),
        sa.Column(
            "operator",
            sa.Enum(
                "EQUALS",
                "NOT_EQUALS",
                "IN",
                "NOT_IN",
                "GREATER_THAN",
                "GREATER_THAN_OR_EQUAL",
                "LESS_THAN",
                "LESS_THAN_OR_EQUAL",
                "EXISTS",
                "NOT_EXISTS",
                name="risk_rule_operator",
            ),
            nullable=False,
        ),
        sa.Column(
            "expected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("score_points", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_scoring_rules_factor_key"),
        "risk_scoring_rules",
        ["factor_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_scoring_rules_is_active"),
        "risk_scoring_rules",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_scoring_rules_priority"),
        "risk_scoring_rules",
        ["priority"],
        unique=False,
    )

    # The task explicitly defines these ranges.
    op.bulk_insert(
        sa.table(
            "risk_score_thresholds",
            sa.column("id", postgresql.UUID(as_uuid=True)),
            sa.column("risk_level", sa.Enum()),
            sa.column("min_score", sa.Integer()),
            sa.column("max_score", sa.Integer()),
            sa.column("is_active", sa.Boolean()),
        ),
        [
            {
                "id": "a82f3f05-a44a-4006-8a67-76d92bbd231f",
                "risk_level": "LOW",
                "min_score": 0,
                "max_score": 30,
                "is_active": True,
            },
            {
                "id": "fb2795f5-548c-425d-8078-b03426c5e81b",
                "risk_level": "MEDIUM",
                "min_score": 31,
                "max_score": 70,
                "is_active": True,
            },
            {
                "id": "a4ef98d1-4f31-4571-acb2-e08591e76cf0",
                "risk_level": "HIGH",
                "min_score": 71,
                "max_score": 100,
                "is_active": True,
            },
        ],
    )

    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'RISK_SCORING_RULE_CREATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS 'RISK_SCORING_RULE_UPDATED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'RISK_SCORING_RULE_STATUS_CHANGED'"
    )
    op.execute(
        "ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS "
        "'CUSTOMER_RISK_SCORE_CALCULATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_risk_profiles", "calculation_details")

    op.drop_index(
        op.f("ix_risk_scoring_rules_priority"), table_name="risk_scoring_rules"
    )
    op.drop_index(
        op.f("ix_risk_scoring_rules_is_active"), table_name="risk_scoring_rules"
    )
    op.drop_index(
        op.f("ix_risk_scoring_rules_factor_key"), table_name="risk_scoring_rules"
    )
    op.drop_table("risk_scoring_rules")
    op.drop_index(
        op.f("ix_risk_score_thresholds_risk_level"), table_name="risk_score_thresholds"
    )
    op.drop_index(
        op.f("ix_risk_score_thresholds_is_active"), table_name="risk_score_thresholds"
    )
    op.drop_table("risk_score_thresholds")
    # ### end Alembic commands ###
