# mypy: ignore-errors

"""update audit_log table

Revision ID: ff0d168f8209
Revises: c03fb87f19fc
Create Date: 2026-08-20 21:21:11.422006

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff0d168f8209"
down_revision: Union[str, Sequence[str], None] = "c03fb87f19fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs", sa.Column("resource_type", sa.String(length=100), nullable=True)
    )
    op.add_column("audit_logs", sa.Column("resource_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_logs", "resource_id")
    op.drop_column("audit_logs", "resource_type")
    # ### end Alembic commands ###
