from datetime import date, datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.utils.enums import (
    AIFunction,
    AIInteractionStatus,
)


class AnalyticsQuestionType(str, Enum):
    CONFIGURED_METRIC = "CONFIGURED_METRIC"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    VERIFICATION_REJECTION_REASONS = "VERIFICATION_REJECTION_REASONS"
    CUSTOMER_REGISTRATIONS = "CUSTOMER_REGISTRATIONS"
    RISK_DISTRIBUTION = "RISK_DISTRIBUTION"
    AML_ALERTS = "AML_ALERTS"
    COMPLIANCE_CASES = "COMPLIANCE_CASES"
    TASK_PERFORMANCE = "TASK_PERFORMANCE"
    WORKFLOW_PERFORMANCE = "WORKFLOW_PERFORMANCE"


class AnalyticsQuestionPlan(BaseModel):
    question_type: AnalyticsQuestionType
    metric_key: str | None = None

    start_date: date
    end_date: date

    comparison_start_date: date
    comparison_end_date: date


class AnalyticsEvidence(BaseModel):
    key: str
    label: str
    value: float | int | str | None
    unit: str | None = None
    source: str

    comparison_value: float | int | str | None = None
    comparison_change_percentage: float | None = None

    details: dict[str, Any] = Field(
        default_factory=dict,
    )


class AIAnalyticsModelResult(BaseModel):
    """
    Structured response returned by the AI model.

    Supporting data is intentionally added by the application
    rather than generated by the model.
    """

    summary: str
    suggested_insights: list[str]
    confidence: float = Field(
        ge=0,
        le=1,
    )


class AIAnalyticsResult(BaseModel):
    summary: str
    supporting_data: list[AnalyticsEvidence]
    suggested_insights: list[str]
    confidence: float = Field(
        ge=0,
        le=1,
    )


class AIAnalyticsResponse(BaseModel):
    interaction_id: UUID
    ai_function: AIFunction
    prompt_id: UUID
    status: AIInteractionStatus

    provider_name: str
    model: str | None
    content: str

    result: AIAnalyticsResult


class AIAnalyticsInteractionResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    user_id: UUID
    ai_function: AIFunction
    prompt_id: UUID
    resource_type: str
    resource_id: UUID
    question: str
    response_data: dict | None
    response_text: str | None
    provider_name: str | None
    model: str | None
    provider_request_id: str | None
    status: AIInteractionStatus
    error_message: str | None
    created_at: datetime
    completed_at: datetime | None
